# Generated by Django 5.2.3 on 2025-06-15 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioOfrecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_servicio', models.CharField(max_length=200)),
                ('descripcion_servicio', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_ofrecidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
