# Generated by Django 5.2.3 on 2025-06-16 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_servicioofrecido'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vacante', models.CharField(max_length=255)),
                ('descripcion_puesto', models.TextField()),
                ('requisitos', models.TextField(help_text='Lista de requisitos, separados por líneas.')),
                ('tipo_contrato', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance/Proyecto')], max_length=50)),
                ('ubicacion', models.CharField(max_length=150)),
                ('salario_ofrecido', models.CharField(blank=True, help_text='Ej: $30,000 - $40,000 MXN mensuales', max_length=100, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_publicadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_postulaciones', to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulantes', to='usuarios.vacanteempresa')),
            ],
            options={
                'unique_together': {('profesional', 'vacante')},
            },
        ),
    ]
