# Generated by Django 5.2.3 on 2025-06-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_vacanteempresa_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
