# Generated by Django 5.2.3 on 2025-08-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En Revisión'), ('contactado', 'Contactado'), ('rechazado', 'Rechazado')], default='recibida', max_length=20),
        ),
    ]
