# Generated by Django 5.2.3 on 2025-08-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_postulacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('calidad_tecnica', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comunicacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('puntualidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('puntualidad_pago', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ambiente_laboral', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('claridad_requerimientos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_hechas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
