# Generated by Django 5.2.3 on 2025-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_reseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='comunicacion',
            new_name='comunicacion_proactiva',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='puntualidad',
            new_name='puntualidad_trabajador',
        ),
        migrations.AddField(
            model_name='reseña',
            name='respeto_horarios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='responsabilidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
