# Generated by Django 5.2.3 on 2025-08-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_comunicacion_reseña_comunicacion_proactiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='Soporte_tecnicoMaterial',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='balance_vida_trabajo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='comunicacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='inclusividad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='recursos_proporcionados',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='transparencia_contractual',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
