# Generated by Django 5.2.3 on 2025-08-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_reseña_soporte_tecnicomaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='atencion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='cumplimiento_estandares',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='eficiencia_tareas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='honestidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='manejo_instrucciones',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='solucion_problemas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
