# Generated by Django 5.2.3 on 2025-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_conversacion_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioofrecido',
            name='imagen_servicio',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
