# Generated by Django 5.2.3 on 2025-08-29 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_servicioofrecido_imagen_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioofrecido',
            name='imagen_servicio',
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios_galeria/')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='usuarios.servicioofrecido')),
            ],
        ),
    ]
