# Generated by Django 5.2.3 on 2025-09-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_servicioofrecido_imagen_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='servicio_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_servicio', to='usuarios.servicioofrecido'),
        ),
    ]
